steps:
  # Build container
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]
  
  # Push image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]

  # Deploy release to Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - release-$COMMIT_SHA
      - --delivery-pipeline=sveltekit-pipeline
      - --region=europe-north1
      - --images=svelte-app=${_IMAGE}
      - --source=./clouddeploy

images:
  - "${_IMAGE}"

options:
  logging: CLOUD_LOGGING_ONLY
  cache: true

substitutions:
  _REGION: "europe-north1"
  _REPO_NAME: "artifacts"
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/sveltekit:latest"