# Cloud Deploy configuration linking to the Cloud Run manifest
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryConfig
metadata:
  name: sveltekit-delivery
render:
  - manifestPath: clouddeploy/cloudrun-service.yaml